#ifndef INPUTS_H
#define	INPUTS_H

/*BUTTONS*/
#define LEFT_BUTTON PORTAbits.RA9
#define RIGHT_BUTTON PORTAbits.RA11
#define SELECTION_BUTTON PORTAbits.RA10
#define POWER_BUTTON PORTAbits.RA2
#define BACKLIGHT_BUTTON PORTAbits.RA3


/*ADC BUFFERS*/
#define SENSOR1BUF       ADC1BUF12
#define SENSOR1AVGBUF    ADC1BUF11
#define SENSOR2BUF       ADC1BUF10
#define SENSOR2AVGBUF    ADC1BUF9
#define SENSOR3BUF       ADC1BUF0
#define SENSOR3AVGBUF    ADC1BUF1
#define SENSOR4BUF       ADC1BUF6
#define SENSOR4VAVGBUF    ADC1BUF16

#define POWER_CIRCUIT_ENABLE PORTAbits.RA8 


#endif	/* INPUTS_H */
